### ISSUE TITLE
It's possible to override existing operational address when calling change_operational_address

### ISSUE THREAD

**Issue by h33333333** [starkware-libs/starknet-staking#6]
There is a check in `stake` that ensures that provided `operational_address` is not used by any other staker:
https://github.com/starkware-libs/starknet-staking/blob/f757b879ebc74de1d02a061ad3dd75166d7d6d60/workspace/apps/staking/contracts/src/staking/staking.cairo#L145-L148

but this check is missing in `change_operational_address` which can lead to operational address override if `operational_address` was already in use by some other staker:
https://github.com/starkware-libs/starknet-staking/blob/f757b879ebc74de1d02a061ad3dd75166d7d6d60/workspace/apps/staking/contracts/src/staking/staking.cairo#L425-L435

**Comment by alon-f** [comment]
Thanks! Acking and updating this was fixed about a month ago.

**Comment by h33333333** [comment]
Great, thanks!
Please close this issue once you update the version.
