### ISSUE TITLE
No event when exit delegation pool

### ISSUE THREAD

**Issue by florian-bellotti** [starkware-libs/starknet-staking#7]
The `exit_delegation_pool_action` entrypoint in the Pool contract does not emit any event to confirm that a member has claimed their withdrawal request.

Additionally, the `remove_from_delegation_pool_action` entrypoint in the Staking contract also lacks event emission, and the function currently contains a 'TODO: Emit event' comment.

**Comment by natan-granit** [comment]
@alon-f , ack on SW side.
will add events, maybe only on one side.

**Comment by alon-f** [comment]
Ack. This will be solved by the time it's on mainnet.
