### ISSUE TITLE
No event when switch delegation pool

### ISSUE THREAD

**Issue by florian-bellotti** [starkware-libs/starknet-staking#8]
The `switch_delegation_pool` entrypoint in the Pool contract does not emit any event to confirm that a delegation pool switch has occurred. Additionally, the function includes a 'TODO: Emit event' comment."

**Comment by natan-granit** [comment]
@alon-f  ack on SW end. Will add the event.

**Comment by alon-f** [comment]
Ack. This will be solved by the time it's on mainnet.
