### ISSUE TITLE
Insufficient ERC20 Balance Error When Claiming Rewards or Withdrawals in Delegation Pool

### ISSUE THREAD

**Issue by florian-bellotti** [starkware-libs/starknet-staking#9]
We are experiencing an issue with the delegation pool we created: `0x011aa7ff466e921c5deb9b0aafb68277a7b5c766635a79fbf0584a2cd2d201f`

Initially, everything worked fine, including deposits, claiming rewards, initiating withdrawals, and claiming withdrawals. However, we are now encountering the following error when trying to claim a withdrawal or rewards: `Insufficient ERC20 balance`

I retried the operation using another account, and it worked as expected. The account that encounters the issue and cannot claim any funds is: `0x5ad30aacd2ef41f64c1c00fb9da8d81f3062069148387af0f34a1cc22319908`.

Note:
I don't have the issue anymore (since block 219000 or a bit less). 

Here is a RPC call to repoduce 
```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "starknet_simulateTransactions",
  "params": {"transactions":[{"sender_address":"0x05ad30aacd2ef41f64c1c00fb9da8d81f3062069148387af0f34a1cc22319908","calldata":[
  "0x1",
  "0x11aa7ff466e921c5deb9b0aafb68277a7b5c766635a79fbf0584a2cd2d201ff",
  "0x89c7b1cc4866e9e58d867cb66844bcc9c17cfdabb8ab640b05d2bc53efc556",
  "0x1",
  "0x5ad30aacd2ef41f64c1c00fb9da8d81f3062069148387af0f34a1cc22319908"
],
 "signature":[],"max_fee":"0x0","version":"0x1","nonce":"0xc3","type":"INVOKE"}],"block_id":{"block_number":218000},"simulation_flags":["SKIP_VALIDATE"]}
}
```

Here is the state_of request at the same block
```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "starknet_call",
  "params": {
      "request":{
          "contract_address": "0x011aa7ff466e921c5deb9b0aafb68277a7b5c766635a79fbf0584a2cd2d201ff",
          "entry_point_selector": "0x01af63b1cdc061704af767c81df4fd9eb5a3d989868ff970dd79d5431a89db44",
          "calldata": ["0x05ad30aacd2ef41f64c1c00fb9da8d81f3062069148387af0f34a1cc22319908"]
      },
      "block_id":{"block_number":218000}}
}
```

**Comment by natan-granit** [comment]
@alon-f , we are investigating, but no findings. Please try the new contracts deployed.

**Comment by alon-f** [comment]
Hi, there were just not enough funds for the rewards in the rewards supplier.
